# Generated by Django 3.2.8 on 2021-10-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0002_alter_tweets_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
