# Generated by Django 3.2.8 on 2021-10-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0003_alter_tweets_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweets',
            options={'ordering': ('-created_at', 'name')},
        ),
    ]
